import { BrowserRouter, Route, Routes } from "react-router-dom";
import { ScrollToTop } from "./components/ScrollToTop";

import Index from "./pages/Index";
import Announcements from "./pages/Announcements";
import Projects from "./pages/Projects";
import ProjectSubmit from "./pages/ProjectSubmit";
import ProjectDetail from "./pages/ProjectDetail";
import { NIP19Page } from "./pages/NIP19Page";
import HashtagPage from "./pages/HashtagPage";
import NotFound from "./pages/NotFound";

export function AppRouter() {
  return (
    <BrowserRouter>
      <ScrollToTop />
      <Routes>
        <Route path="/" element={<Index />} />
        <Route path="/announcements" element={<Announcements />} />
        <Route path="/projects" element={<Projects />} />
        <Route path="/projects/submit" element={<ProjectSubmit />} />
        <Route path="/projects/:naddr" element={<ProjectDetail />} />
        {/* Hashtag route (generated by NoteContent) */}
        <Route path="/t/:hashtag" element={<HashtagPage />} />
        {/* NIP-19 route for npub1, note1, naddr1, nevent1, nprofile1 */}
        <Route path="/:nip19" element={<NIP19Page />} />
        {/* ADD ALL CUSTOM ROUTES ABOVE THE CATCH-ALL "*" ROUTE */}
        <Route path="*" element={<NotFound />} />
      </Routes>
    </BrowserRouter>
  );
}
export default AppRouter;
